### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by jayvdb** [StyXman/pefan#1]
Do you intend to release this on PyPI?
It seems to be at least alpha quality, probably beta.

**Comment by StyXman** [comment]
Your wish is my command:

https://pypi.org/project/pefan/

https://github.com/StyXman/pefan/releases/tag/v0.1a

**Comment by jayvdb** [comment]
Thanks.  Packaging test run at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pefan

Next step is creating tests ... :+1: 

fwiw, I have been looking through lots of similar tools written in Python, looking for the 'best', and your one wins in versatility wrt command line switches emulating perl.

In https://build.opensuse.org/project/show/home:jayvdb:py-new you'll find my little collection, including

- python-pyle
- python-pefan
- python-bsed
- python-fsed
- python-pyin
- python-pythonpy
- python-repex
- python-pawk
- python-pyline
- python-aina
- python-py1cmd
- python-tabtools
- python-osh
- python-python-awk
- python-awk
- python-pyfil
- python-sar-tool
- python-qrep
- python-pysed
- python-repren
- python-spy-cli
- python-pyf-programmers-find
- python-py3line
- python-rextract
- python-greptools
- python-sed
- python-codemod
- python-subst
